Repository Bhavya1352/eventmappr, pull requests merged in 2025-08, with the labels that each got.

#346 Improved UI of Near By Page
  pages/nearby.js
Labels: SSoC25, Advanced

#356 Improved UI of Tourist Places
  src/components/sections/TouristPlacesSection.js
Labels: SSoC25, Advanced

#370 Improved UI of About Page
  pages/about.js
Labels: SSoC25, Intermediate

#382 Changed the form bg as theme
  components/sections/FAQSection.js
Labels: Intermediate, GSSOC25

#389 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: Intermediate, GSSOC25

#390 user backend added
  Backend/controllers/user.controller.js
  Backend/middlewares/auth.js
  Backend/middlewares/auth.middleware.js
  Backend/models/user.model.js
  Backend/package-lock.json
  Backend/package.json
  Backend/routes/user.routes.js
Labels: Advanced, GSSOC25

#394 pr create automate message added
  .github/workflows/pr-create-automate-message.yml
Labels: SSoC25, Intermediate

#395 added underline smooth hover effects to footer elements
  components/layout/Footer.js
Labels: SSoC25, Beginner

#401 Initial commit - currency converter
  pages/CurrencyConverter.css
  pages/currency-converter.js
Labels: Intermediate, GSSOC25

#399 [ENHANCE]: color enhance of explore btn
  components/sections/HeroSection.js
Labels: SSoC25, Beginner, GSSOC25

#412 issue #366 add map view for event location
  components/map/MapExplorer.js
  components/map/NearbyPlaces.js
Labels: Advanced, GSSOC25

#421 fix(cursor): correct color in light and dark mode
  components/Cursor.jsx
Labels: SSoC25, Beginner

#419 event controller added
  Backend/controllers/event.controller.js
Labels: Advanced, GSSOC25

#428 currency ui
  pages/currency-converter.js
Labels: SSoC25, Intermediate

#432 feat: Add dark mode support for splash screen
  components/LoadingSpinner.js
Labels: SSoC25, Beginner

#435 removed duplicate button
  components/map/MapExplorer.js
  components/sections/HeroSection.js
Labels: SSoC25, Beginner

#449 event routes created for event controller
  Backend/app.min.js
  Backend/routes/event.routes.js
Labels: SSoC25, Advanced

#451 Added Event Gallery page
  src/App.js
  src/components/layout/Navbar.js
  src/pages/EventGallery.js
  src/pages/HomePage.js
  styles/globals.css
Labels: Intermediate, GSSOC25
